//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.21 at 01:09:03 PM CDT 
//


package mx.santander.liquidez.control.resolver.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getLocalUserFromCorpID complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getLocalUserFromCorpID"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="reqUsrLDAP" type="{http://ws.resolver.isban.mx/}requestCorporativo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getLocalUserFromCorpID", propOrder = {
    "reqUsrLDAP"
})
public class GetLocalUserFromCorpID {

    protected RequestCorporativo reqUsrLDAP;

    /**
     * Gets the value of the reqUsrLDAP property.
     * 
     * @return
     *     possible object is
     *     {@link RequestCorporativo }
     *     
     */
    public RequestCorporativo getReqUsrLDAP() {
        return reqUsrLDAP;
    }

    /**
     * Sets the value of the reqUsrLDAP property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestCorporativo }
     *     
     */
    public void setReqUsrLDAP(RequestCorporativo value) {
        this.reqUsrLDAP = value;
    }

}
