//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.21 at 01:09:03 PM CDT 
//


package mx.santander.liquidez.control.resolver.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.santander.liquidez.control.resolver.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetCommonNameFromCorpID_QNAME = new QName("http://ws.resolver.isban.mx/", "getCommonNameFromCorpID");
    private final static QName _GetCommonNameFromCorpIDResponse_QNAME = new QName("http://ws.resolver.isban.mx/", "getCommonNameFromCorpIDResponse");
    private final static QName _GetCorporateUserFromLocalID_QNAME = new QName("http://ws.resolver.isban.mx/", "getCorporateUserFromLocalID");
    private final static QName _GetCorporateUserFromLocalIDResponse_QNAME = new QName("http://ws.resolver.isban.mx/", "getCorporateUserFromLocalIDResponse");
    private final static QName _GetEmailFromCorpID_QNAME = new QName("http://ws.resolver.isban.mx/", "getEmailFromCorpID");
    private final static QName _GetEmailFromCorpIDResponse_QNAME = new QName("http://ws.resolver.isban.mx/", "getEmailFromCorpIDResponse");
    private final static QName _GetLocalUserFromCorpID_QNAME = new QName("http://ws.resolver.isban.mx/", "getLocalUserFromCorpID");
    private final static QName _GetLocalUserFromCorpIDResponse_QNAME = new QName("http://ws.resolver.isban.mx/", "getLocalUserFromCorpIDResponse");
    private final static QName _GetLocationFromCorpID_QNAME = new QName("http://ws.resolver.isban.mx/", "getLocationFromCorpID");
    private final static QName _GetLocationFromCorpIDResponse_QNAME = new QName("http://ws.resolver.isban.mx/", "getLocationFromCorpIDResponse");
    private final static QName _GetPositionFromCorpID_QNAME = new QName("http://ws.resolver.isban.mx/", "getPositionFromCorpID");
    private final static QName _GetPositionFromCorpIDResponse_QNAME = new QName("http://ws.resolver.isban.mx/", "getPositionFromCorpIDResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.santander.liquidez.control.resolver.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCommonNameFromCorpID }
     * 
     */
    public GetCommonNameFromCorpID createGetCommonNameFromCorpID() {
        return new GetCommonNameFromCorpID();
    }

    /**
     * Create an instance of {@link GetCommonNameFromCorpIDResponse }
     * 
     */
    public GetCommonNameFromCorpIDResponse createGetCommonNameFromCorpIDResponse() {
        return new GetCommonNameFromCorpIDResponse();
    }

    /**
     * Create an instance of {@link GetCorporateUserFromLocalID }
     * 
     */
    public GetCorporateUserFromLocalID createGetCorporateUserFromLocalID() {
        return new GetCorporateUserFromLocalID();
    }

    /**
     * Create an instance of {@link GetCorporateUserFromLocalIDResponse }
     * 
     */
    public GetCorporateUserFromLocalIDResponse createGetCorporateUserFromLocalIDResponse() {
        return new GetCorporateUserFromLocalIDResponse();
    }

    /**
     * Create an instance of {@link GetEmailFromCorpID }
     * 
     */
    public GetEmailFromCorpID createGetEmailFromCorpID() {
        return new GetEmailFromCorpID();
    }

    /**
     * Create an instance of {@link GetEmailFromCorpIDResponse }
     * 
     */
    public GetEmailFromCorpIDResponse createGetEmailFromCorpIDResponse() {
        return new GetEmailFromCorpIDResponse();
    }

    /**
     * Create an instance of {@link GetLocalUserFromCorpID }
     * 
     */
    public GetLocalUserFromCorpID createGetLocalUserFromCorpID() {
        return new GetLocalUserFromCorpID();
    }

    /**
     * Create an instance of {@link GetLocalUserFromCorpIDResponse }
     * 
     */
    public GetLocalUserFromCorpIDResponse createGetLocalUserFromCorpIDResponse() {
        return new GetLocalUserFromCorpIDResponse();
    }

    /**
     * Create an instance of {@link GetLocationFromCorpID }
     * 
     */
    public GetLocationFromCorpID createGetLocationFromCorpID() {
        return new GetLocationFromCorpID();
    }

    /**
     * Create an instance of {@link GetLocationFromCorpIDResponse }
     * 
     */
    public GetLocationFromCorpIDResponse createGetLocationFromCorpIDResponse() {
        return new GetLocationFromCorpIDResponse();
    }

    /**
     * Create an instance of {@link GetPositionFromCorpID }
     * 
     */
    public GetPositionFromCorpID createGetPositionFromCorpID() {
        return new GetPositionFromCorpID();
    }

    /**
     * Create an instance of {@link GetPositionFromCorpIDResponse }
     * 
     */
    public GetPositionFromCorpIDResponse createGetPositionFromCorpIDResponse() {
        return new GetPositionFromCorpIDResponse();
    }

    /**
     * Create an instance of {@link RequestCorporativo }
     * 
     */
    public RequestCorporativo createRequestCorporativo() {
        return new RequestCorporativo();
    }

    /**
     * Create an instance of {@link RequestLDAP }
     * 
     */
    public RequestLDAP createRequestLDAP() {
        return new RequestLDAP();
    }

    /**
     * Create an instance of {@link ResponseConsultaUsrLDAP }
     * 
     */
    public ResponseConsultaUsrLDAP createResponseConsultaUsrLDAP() {
        return new ResponseConsultaUsrLDAP();
    }

    /**
     * Create an instance of {@link RequestLocal }
     * 
     */
    public RequestLocal createRequestLocal() {
        return new RequestLocal();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCommonNameFromCorpID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.resolver.isban.mx/", name = "getCommonNameFromCorpID")
    public JAXBElement<GetCommonNameFromCorpID> createGetCommonNameFromCorpID(GetCommonNameFromCorpID value) {
        return new JAXBElement<GetCommonNameFromCorpID>(_GetCommonNameFromCorpID_QNAME, GetCommonNameFromCorpID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCommonNameFromCorpIDResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.resolver.isban.mx/", name = "getCommonNameFromCorpIDResponse")
    public JAXBElement<GetCommonNameFromCorpIDResponse> createGetCommonNameFromCorpIDResponse(GetCommonNameFromCorpIDResponse value) {
        return new JAXBElement<GetCommonNameFromCorpIDResponse>(_GetCommonNameFromCorpIDResponse_QNAME, GetCommonNameFromCorpIDResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCorporateUserFromLocalID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.resolver.isban.mx/", name = "getCorporateUserFromLocalID")
    public JAXBElement<GetCorporateUserFromLocalID> createGetCorporateUserFromLocalID(GetCorporateUserFromLocalID value) {
        return new JAXBElement<GetCorporateUserFromLocalID>(_GetCorporateUserFromLocalID_QNAME, GetCorporateUserFromLocalID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCorporateUserFromLocalIDResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.resolver.isban.mx/", name = "getCorporateUserFromLocalIDResponse")
    public JAXBElement<GetCorporateUserFromLocalIDResponse> createGetCorporateUserFromLocalIDResponse(GetCorporateUserFromLocalIDResponse value) {
        return new JAXBElement<GetCorporateUserFromLocalIDResponse>(_GetCorporateUserFromLocalIDResponse_QNAME, GetCorporateUserFromLocalIDResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmailFromCorpID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.resolver.isban.mx/", name = "getEmailFromCorpID")
    public JAXBElement<GetEmailFromCorpID> createGetEmailFromCorpID(GetEmailFromCorpID value) {
        return new JAXBElement<GetEmailFromCorpID>(_GetEmailFromCorpID_QNAME, GetEmailFromCorpID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmailFromCorpIDResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.resolver.isban.mx/", name = "getEmailFromCorpIDResponse")
    public JAXBElement<GetEmailFromCorpIDResponse> createGetEmailFromCorpIDResponse(GetEmailFromCorpIDResponse value) {
        return new JAXBElement<GetEmailFromCorpIDResponse>(_GetEmailFromCorpIDResponse_QNAME, GetEmailFromCorpIDResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLocalUserFromCorpID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.resolver.isban.mx/", name = "getLocalUserFromCorpID")
    public JAXBElement<GetLocalUserFromCorpID> createGetLocalUserFromCorpID(GetLocalUserFromCorpID value) {
        return new JAXBElement<GetLocalUserFromCorpID>(_GetLocalUserFromCorpID_QNAME, GetLocalUserFromCorpID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLocalUserFromCorpIDResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.resolver.isban.mx/", name = "getLocalUserFromCorpIDResponse")
    public JAXBElement<GetLocalUserFromCorpIDResponse> createGetLocalUserFromCorpIDResponse(GetLocalUserFromCorpIDResponse value) {
        return new JAXBElement<GetLocalUserFromCorpIDResponse>(_GetLocalUserFromCorpIDResponse_QNAME, GetLocalUserFromCorpIDResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLocationFromCorpID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.resolver.isban.mx/", name = "getLocationFromCorpID")
    public JAXBElement<GetLocationFromCorpID> createGetLocationFromCorpID(GetLocationFromCorpID value) {
        return new JAXBElement<GetLocationFromCorpID>(_GetLocationFromCorpID_QNAME, GetLocationFromCorpID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLocationFromCorpIDResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.resolver.isban.mx/", name = "getLocationFromCorpIDResponse")
    public JAXBElement<GetLocationFromCorpIDResponse> createGetLocationFromCorpIDResponse(GetLocationFromCorpIDResponse value) {
        return new JAXBElement<GetLocationFromCorpIDResponse>(_GetLocationFromCorpIDResponse_QNAME, GetLocationFromCorpIDResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPositionFromCorpID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.resolver.isban.mx/", name = "getPositionFromCorpID")
    public JAXBElement<GetPositionFromCorpID> createGetPositionFromCorpID(GetPositionFromCorpID value) {
        return new JAXBElement<GetPositionFromCorpID>(_GetPositionFromCorpID_QNAME, GetPositionFromCorpID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPositionFromCorpIDResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.resolver.isban.mx/", name = "getPositionFromCorpIDResponse")
    public JAXBElement<GetPositionFromCorpIDResponse> createGetPositionFromCorpIDResponse(GetPositionFromCorpIDResponse value) {
        return new JAXBElement<GetPositionFromCorpIDResponse>(_GetPositionFromCorpIDResponse_QNAME, GetPositionFromCorpIDResponse.class, null, value);
    }

}
